Repository CSCI3308-Group7-Book-Tracker/book-tracker, pull requests merged in 2023-11, with the labels that each got.

#10 added template directory with placeholders to be removed as needed
  Milestone-Submissions/placeholder.txt
  Project-Code/.gitignore
  Project-Code/docker-compose.yaml
  Project-Code/src/index.js
  Project-Code/src/init_data/placeholder.txt
  Project-Code/src/package.json
  Project-Code/src/resources/css/placeholder.txt
  Project-Code/src/resources/img/placeholder.txt
  Project-Code/src/resources/js/placeholder.txt
  Project-Code/src/test/placeholder.txt
  Project-Code/src/views/pages/placeholder.txt
  Project-Code/src/views/partials/placeholder.txt
  Team-Meeting-Logs/placeholder.txt
Labels: Story

#13 Issue 11-creating menu partial
  Project-Code/src/views/partials/menu.ejs
Labels: Story

#17 finished header
  Project-Code/src/views/partials/header.ejs
Labels: Story

#20 created login and register pages, updated index.js
  Project-Code/src/index.js
  Project-Code/src/views/pages/login.ejs
  Project-Code/src/views/pages/placeholder.txt
  Project-Code/src/views/pages/register.ejs
  Project-Code/src/views/partials/placeholder.txt
Labels: Story

#28 Adding Database Creation
  Project-Code/docker-compose.yaml
  Project-Code/src/init_data/create.sql
  Project-Code/src/init_data/placeholder.txt
Labels: Story

#35 server startup config
  Project-Code/.gitignore
  Project-Code/docker-compose.yaml
  Project-Code/src/package.json
  Project-Code/src/test/placeholder.txt
  Project-Code/src/test/server.spec.js
  Project-Code/src/views/pages/login.ejs
  Project-Code/src/views/pages/register.ejs
Labels: Story

#37 completed lab 11 requirements, unit tests added
  Project-Code/src/databaseModule.js
  Project-Code/src/index.js
  Project-Code/src/init_data/create.sql
  Project-Code/src/package.json
  Project-Code/src/test/server.spec.js
  Project-Code/src/test/test-setup.js
  Project-Code/src/views/pages/login.ejs
  Project-Code/src/views/pages/register.ejs
  Project-Code/src/views/partials/message.ejs
Labels: Story

#41 Explore Page JS Routes and Google Books API
  Project-Code/src/index.js
  Project-Code/src/views/pages/explore.ejs
Labels: Story

#49 adding in progress/completed boolean to users_to_books table
  Project-Code/src/init_data/create.sql
Labels: Story

#53 added welcome page, change styles if necessary
  Project-Code/src/index.js
  Project-Code/src/resources/css/placeholder.txt
  Project-Code/src/resources/css/welcome.css
  Project-Code/src/resources/img/egyptParchment.jpg
  Project-Code/src/resources/img/placeholder.txt
  Project-Code/src/views/pages/welcome.ejs
Labels: Story

#62 Week 2 Meeting Notes
  Milestone-Submissions/week2meeting.txt
Labels: Documentation

#61 Create week2
  Milestone-Submissions/Releases/week2
Labels: Documentation

#66 38 explore page api
  Project-Code/src/index.js
  Project-Code/src/views/pages/explore.ejs
Labels: Bug

#56 added profile framework and updated index
  Project-Code/src/index.js
  Project-Code/src/views/pages/profile.ejs
  Project-Code/src/views/partials/menu.ejs
Labels: Story

#69 simple bugfix
  Project-Code/src/index.js
Labels: Bug

#72 added dynamic modals to explore page, basic linting
  Project-Code/src/views/pages/explore.ejs
Labels: Story

#75 minor change to explore page searchbar
  Project-Code/src/views/pages/explore.ejs
Labels: Story

#82 initialization and null catching for explore page
  Project-Code/src/views/pages/explore.ejs
Labels: Story

#60 57 login register redesign
  Project-Code/src/resources/css/welcome.css
  Project-Code/src/views/pages/login.ejs
  Project-Code/src/views/pages/register.ejs
Labels: Story

#88 fixed login redirect
  Project-Code/src/index.js
Labels: Bug
