Repository CSCI3308-Group7-Book-Tracker/book-tracker, pull requests merged in 2023-12, with the labels that each got.

#103 adding user_to_friend
  Project-Code/src/init_data/create.sql
Labels: Story

#109 Overhaul of code to support reviews
  Project-Code/src/index.js
  Project-Code/src/init_data/create.sql
  Project-Code/src/views/pages/collections.ejs
  Project-Code/src/views/pages/explore.ejs
  Project-Code/src/views/pages/stats.ejs
  Project-Code/src/views/partials/menu.ejs
Labels: Story

#113 serviced static jpg for welcome page
  Project-Code/src/index.js
  Project-Code/src/views/pages/welcome.ejs
Labels: Bug

#118 styling overhaul!
  Project-Code/src/views/pages/collections.ejs
  Project-Code/src/views/pages/explore.ejs
  Project-Code/src/views/pages/login.ejs
  Project-Code/src/views/pages/profile.ejs
  Project-Code/src/views/pages/register.ejs
  Project-Code/src/views/pages/welcome.ejs
  Project-Code/src/views/partials/footer.ejs
  Project-Code/src/views/partials/header.ejs
  Project-Code/src/views/partials/menu.ejs
Labels: Story

#117 Add week4 meeting minutes
  Team-Meeting-Logs/Meeting minutes for 12.6.txt
Labels: Documentation

#119 completed friends system, implemented changes across all pages
  Project-Code/src/index.js
  Project-Code/src/init_data/create.sql
  Project-Code/src/views/pages/explore.ejs
  Project-Code/src/views/pages/profile.ejs
  Project-Code/src/views/partials/header.ejs
Labels: Story

#122 add week4 release notes
  Milestone-Submissions/Releases/week4
Labels: Documentation

#123 masked register password
  Project-Code/src/views/pages/register.ejs
Labels: Story

#126 Added deployment link
  README.md
Labels: Documentation

#125 Final Report
  Milestone-Submissions/ProjectReport_7.pdf
Labels: Documentation
